### ISSUE TITLE
Hi, the extension cant run

### ISSUE THREAD

**Issue by BrayantVideos1** [AngaBlue/rlg-trade-bumper#6]
it says Failed to load background script 'background.js' when i try to install it.

**Comment by AngaBlue** [comment]
It sounds like you didn't build it.  Run the build script and give it another go.

**Comment by BrayantVideos1** [comment]
how can i do that? 

thanks for helping!

**Comment by AngaBlue** [comment]
You can run the build script using:
```
npm run build
```

**Comment by BrayantVideos1** [comment]
it gives me errors to build it

**Comment by AngaBlue** [comment]
In order for me to help you, I need some more information.  When posting issues on GitHub, it's common courtesy to outline the steps that you took to get to the error and what your environment is.  It's also vital that you include the actual error you face, meaning copy pasting the error and stack trace into your message.

**Comment by BrayantVideos1** [comment]
sure, my bad, those are the errors that i get when i run "npm run build" (os: windows 10):

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v11.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle rlg-trade-bumper@0.1.2~prebuild: rlg-trade-bumper@0.1.2
6 info lifecycle rlg-trade-bumper@0.1.2~build: rlg-trade-bumper@0.1.2
7 verbose lifecycle rlg-trade-bumper@0.1.2~build: unsafe-perm in lifecycle true
8 verbose lifecycle rlg-trade-bumper@0.1.2~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\Programas\Bots\rlg-trade-bumper-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;E:\Programas\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Users\Brayant\AppData\Local\Microsoft\WindowsApps;;C:\Users\Brayant\spicetify-cli;C:\Users\Brayant\AppData\Local\Programs\Lux;C:\Users\Brayant\AppData\Local\Programs\Lux;C:\Users\Brayant\AppData\Local\Programs\Lux;C:\Users\Brayant\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\Brayant\AppData\Roaming\npm
9 verbose lifecycle rlg-trade-bumper@0.1.2~build: CWD: H:\Programas\Bots\rlg-trade-bumper-master
10 silly lifecycle rlg-trade-bumper@0.1.2~build: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env NODE_ENV=production webpack --mode production' ]
11 silly lifecycle rlg-trade-bumper@0.1.2~build: Returned: code: 2  signal: null
12 info lifecycle rlg-trade-bumper@0.1.2~build: Failed to exec build script
13 verbose stack Error: rlg-trade-bumper@0.1.2 build: `cross-env NODE_ENV=production webpack --mode production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid rlg-trade-bumper@0.1.2
15 verbose cwd H:\Programas\Bots\rlg-trade-bumper-master
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v11.0.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error rlg-trade-bumper@0.1.2 build: `cross-env NODE_ENV=production webpack --mode production`
22 error Exit status 2
23 error Failed at the rlg-trade-bumper@0.1.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by AngaBlue** [comment]
I've googled your issue, I'd give this a go: [https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle](https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle )

If that doesn't fix the issue, I'd also try it again with a newer version of node.

**Comment by BrayantVideos1** [comment]
i investigated, and went deep into this, the resoult is my cmd files are corrupted. Thanks for helping!.
